version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy-job:
   branches:
      only:
        - master
    executor:
      name: node/default
    commands:
          - ./deploy.sh
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
              name: Deploy Script
              commands:
                - ../build/deploy.sh`
workflows:
    build-and-test:
      jobs:
        - deploy-job