version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy-job:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "08 76 40 80 9E FF CD B5 42 FB B5 16 DC 2F BF E3 CF 2E 6F AD 8D 06 F1 33 BC 17 4C C3 A7 4E 62 4B"
      - run:
          name: Deploy Script
          commands:
            - ../build/deploy.sh`
workflows:
  build-and-test:
    jobs:
      - deploy-job
